title: CarbonClick System Status
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Climate Friendly Cart App (Shopify)
      link: https://apps.shopify.com/carbonclick
    - name: API
    - name: My CarbonClick
      link: http://my.carbon.click/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " New Zealand Standard Time"
  logo: /images/uploads/cc_mark_green.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    carbonclick.com' href='https://www.carbonclick.com/'
    target='_blank'>CarbonClick</a> systems operations.<br /> Subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  copyrightHolder: CarbonClick Limited
  eventsPerPage: 10
  iconType: image/png
  groups:
    - All
  icon: /images/clearstatus.png
  description_footer: Visit <a class='text-grey-darkest' title='Visit
    carbonclick.com' href='https://www.carbonclick.com/'
    target='_blank'>carbonclick.com</a> to find out how you can make your
    business more climate friendly
